# Generated by Django 4.1.1 on 2022-09-13 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('gpa_back', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterventionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('label', models.CharField(max_length=255, null=True, verbose_name="Nom type d'intervention")),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Crée le')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Crée le')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Crée le')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Crée le')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('label', models.CharField(blank=True, max_length=255, verbose_name='Role')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='car',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='car',
            name='published',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Crée le'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='type',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Type du véhicule'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Crée le'),
        ),
        migrations.AddField(
            model_name='historicalcar',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalcar',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='historicalcar',
            name='published',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='Crée le'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcar',
            name='type',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Type du véhicule'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcar',
            name='updated',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='Crée le'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Marque / Fabriquant'),
        ),
        migrations.AlterField(
            model_name='car',
            name='serial_number',
            field=models.CharField(max_length=255, verbose_name='Numéro Matricule'),
        ),
        migrations.AlterField(
            model_name='historicalcar',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Marque / Fabriquant'),
        ),
        migrations.AlterField(
            model_name='historicalcar',
            name='serial_number',
            field=models.CharField(max_length=255, verbose_name='Numéro Matricule'),
        ),
        migrations.CreateModel(
            name='UserProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gpa_back.userrole', verbose_name='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('begin_date', models.DateField(max_length=255)),
                ('end_date', models.DateField(max_length=255)),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Crée le')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Crée le')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RaceApplicant', to='gpa_back.userprofil', verbose_name='Demandeur de la course')),
                ('car_concerned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpa_back.car', verbose_name='véhicule concerné')),
                ('steed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RaceSteed', to='gpa_back.userprofil', verbose_name='Coursier exécutant la course')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('date', models.DateField(max_length=255)),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Crée le')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Crée le')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpa_back.userprofil', verbose_name="Demandeur de l'intervention")),
                ('car_concerned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpa_back.car', verbose_name="véhicule concerné par l'intervention")),
                ('type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gpa_back.interventiontype', verbose_name="Type de l'intervention")),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalUserRole',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('label', models.CharField(blank=True, max_length=255, verbose_name='Role')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical user role',
                'verbose_name_plural': 'historical user roles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalUserProfil',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gpa_back.userrole', verbose_name='')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical user profil',
                'verbose_name_plural': 'historical user profils',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRace',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('begin_date', models.DateField(max_length=255)),
                ('end_date', models.DateField(max_length=255)),
                ('published', models.DateTimeField(blank=True, editable=False, verbose_name='Crée le')),
                ('updated', models.DateTimeField(blank=True, editable=False, verbose_name='Crée le')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('applicant', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gpa_back.userprofil', verbose_name='Demandeur de la course')),
                ('car_concerned', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gpa_back.car', verbose_name='véhicule concerné')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('steed', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gpa_back.userprofil', verbose_name='Coursier exécutant la course')),
            ],
            options={
                'verbose_name': 'historical race',
                'verbose_name_plural': 'historical races',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProject',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('published', models.DateTimeField(blank=True, editable=False, verbose_name='Crée le')),
                ('updated', models.DateTimeField(blank=True, editable=False, verbose_name='Crée le')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical project',
                'verbose_name_plural': 'historical projects',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalInterventionType',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('label', models.CharField(max_length=255, null=True, verbose_name="Nom type d'intervention")),
                ('published', models.DateTimeField(blank=True, editable=False, verbose_name='Crée le')),
                ('updated', models.DateTimeField(blank=True, editable=False, verbose_name='Crée le')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical intervention type',
                'verbose_name_plural': 'historical intervention types',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalIntervention',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('date', models.DateField(max_length=255)),
                ('published', models.DateTimeField(blank=True, editable=False, verbose_name='Crée le')),
                ('updated', models.DateTimeField(blank=True, editable=False, verbose_name='Crée le')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('applicant', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gpa_back.userprofil', verbose_name="Demandeur de l'intervention")),
                ('car_concerned', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gpa_back.car', verbose_name="véhicule concerné par l'intervention")),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gpa_back.interventiontype', verbose_name="Type de l'intervention")),
            ],
            options={
                'verbose_name': 'historical intervention',
                'verbose_name_plural': 'historical interventions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Crée le')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Crée le')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['content_type', 'object_id'], name='gpa_back_do_content_31b175_idx'),
        ),
    ]
