# Generated by Django 4.1.1 on 2022-09-13 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gpa_back', '0002_interventiontype_project_userrole_car_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalintervention',
            name='project',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gpa_back.project', verbose_name="Projet de l'intervention"),
        ),
        migrations.AddField(
            model_name='historicalrace',
            name='project',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gpa_back.project', verbose_name='Projet de la course'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gpa_back.project', verbose_name="Projet de l'intervention"),
        ),
        migrations.AddField(
            model_name='race',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gpa_back.project', verbose_name='Projet de la course'),
        ),
    ]
