# Generated by Django 4.1.1 on 2022-09-13 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpa_back', '0004_alter_historicaluserprofil_role_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['manufacturer'], 'verbose_name': 'Véhicule', 'verbose_name_plural': 'Véhicules'},
        ),
        migrations.AlterModelOptions(
            name='historicalcar',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Véhicule', 'verbose_name_plural': 'historical Véhicules'},
        ),
        migrations.AlterModelOptions(
            name='historicalintervention',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Intervention', 'verbose_name_plural': 'historical Interventions'},
        ),
        migrations.AlterModelOptions(
            name='historicalinterventiontype',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': "historical Type d'Intervention", 'verbose_name_plural': "historical Types d'Interventions"},
        ),
        migrations.AlterModelOptions(
            name='historicalproject',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Projet', 'verbose_name_plural': 'historical Projets'},
        ),
        migrations.AlterModelOptions(
            name='historicalrace',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Course', 'verbose_name_plural': 'historical Courses'},
        ),
        migrations.AlterModelOptions(
            name='historicaluserprofil',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Profil utilisateur', 'verbose_name_plural': 'historical Profils utilisateurs'},
        ),
        migrations.AlterModelOptions(
            name='historicaluserrole',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Roles utilisateurs', 'verbose_name_plural': 'historical Roles utilisateurs'},
        ),
        migrations.AlterModelOptions(
            name='intervention',
            options={'ordering': ['project', 'type'], 'verbose_name': 'Intervention', 'verbose_name_plural': 'Interventions'},
        ),
        migrations.AlterModelOptions(
            name='interventiontype',
            options={'ordering': ['label'], 'verbose_name': "Type d'Intervention", 'verbose_name_plural': "Types d'Interventions"},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['label'], 'verbose_name': 'Projet', 'verbose_name_plural': 'Projets'},
        ),
        migrations.AlterModelOptions(
            name='race',
            options={'ordering': ['project', 'car_concerned', 'applicant'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='userprofil',
            options={'ordering': ['user', 'role'], 'verbose_name': 'Profil utilisateur', 'verbose_name_plural': 'Profils utilisateurs'},
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={'ordering': ['label'], 'verbose_name': 'Roles utilisateurs', 'verbose_name_plural': 'Roles utilisateurs'},
        ),
        migrations.AlterModelTable(
            name='car',
            table='cars',
        ),
        migrations.AlterModelTable(
            name='intervention',
            table='interventions',
        ),
        migrations.AlterModelTable(
            name='interventiontype',
            table='intervention_types',
        ),
        migrations.AlterModelTable(
            name='project',
            table='projects',
        ),
        migrations.AlterModelTable(
            name='race',
            table='races',
        ),
        migrations.AlterModelTable(
            name='userprofil',
            table='user_profil',
        ),
        migrations.AlterModelTable(
            name='userrole',
            table='user_roles',
        ),
    ]
