# Generated by Django 4.1.1 on 2022-09-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpa_back', '0005_alter_car_options_alter_historicalcar_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrace',
            name='destination',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='destination',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalrace',
            name='begin_date',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalrace',
            name='end_date',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='begin_date',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='end_date',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
    ]
