# Generated by Django 4.1.1 on 2022-09-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpa_back', '0006_historicalrace_destination_race_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrace',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Motif de la course'),
        ),
        migrations.AddField(
            model_name='race',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Motif de la course'),
        ),
    ]
