# Generated by Django 4.1.1 on 2022-09-13 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gpa_back', '0007_historicalrace_reason_race_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalintervention',
            name='status',
            field=models.CharField(blank=True, choices=[('APPROUVED', 'approuved'), ('REFUSED', 'refused'), ('PENDING', 'pending')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalrace',
            name='status',
            field=models.CharField(blank=True, choices=[('APPROUVED', 'approuved'), ('REFUSED', 'refused'), ('PENDING', 'pending')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='status',
            field=models.CharField(blank=True, choices=[('APPROUVED', 'approuved'), ('REFUSED', 'refused'), ('PENDING', 'pending')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='status',
            field=models.CharField(blank=True, choices=[('APPROUVED', 'approuved'), ('REFUSED', 'refused'), ('PENDING', 'pending')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalrace',
            name='begin_date',
            field=models.DateField(blank=True, max_length=255, null=True, verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='historicalrace',
            name='destination',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Destination'),
        ),
        migrations.AlterField(
            model_name='historicalrace',
            name='end_date',
            field=models.DateField(blank=True, max_length=255, null=True, verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='historicalrace',
            name='project',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gpa_back.project', verbose_name='Projet concerné'),
        ),
        migrations.AlterField(
            model_name='race',
            name='begin_date',
            field=models.DateField(blank=True, max_length=255, null=True, verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='race',
            name='destination',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Destination'),
        ),
        migrations.AlterField(
            model_name='race',
            name='end_date',
            field=models.DateField(blank=True, max_length=255, null=True, verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='race',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gpa_back.project', verbose_name='Projet concerné'),
        ),
    ]
