# Generated by Django 4.1.1 on 2022-09-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpa_back', '0008_historicalintervention_status_historicalrace_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalintervention',
            name='status',
            field=models.CharField(blank=True, choices=[('APPROUVED', 'approuvé'), ('REFUSED', 'refusé'), ('PENDING', 'en attente')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalrace',
            name='status',
            field=models.CharField(blank=True, choices=[('APPROUVED', 'approuvé'), ('REFUSED', 'refusé'), ('PENDING', 'en attente')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='status',
            field=models.CharField(blank=True, choices=[('APPROUVED', 'approuvé'), ('REFUSED', 'refusé'), ('PENDING', 'en attente')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='status',
            field=models.CharField(blank=True, choices=[('APPROUVED', 'approuvé'), ('REFUSED', 'refusé'), ('PENDING', 'en attente')], max_length=15, null=True),
        ),
    ]
