# Generated by Django 4.1.1 on 2022-09-13 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gpa_back', '0009_alter_historicalintervention_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpa_back.interventiontype', verbose_name="Type de l'intervention"),
        ),
    ]
