# Generated by Django 4.1.1 on 2022-09-13 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gpa_back', '0011_alter_historicalintervention_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RaceApplicant', to='gpa_back.userprofil', verbose_name='Demandeur de la course'),
        ),
        migrations.AlterField(
            model_name='race',
            name='car_concerned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gpa_back.car', verbose_name='véhicule concerné'),
        ),
        migrations.AlterField(
            model_name='race',
            name='steed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RaceSteed', to='gpa_back.userprofil', verbose_name='Coursier exécutant la course'),
        ),
    ]
